trigger:
  - master

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Instalar_Maven
    steps:
      - task: Maven@3
        inputs:
        mavenPomFile: "pom.xml"
        mavenOptions: "-Xmx3072m"
        javaHomeOption: "JDKVersion"
        jdkVersionOption: "1.8"
        jdkArchitectureOption: "x64"
        publishJUnitResults: true
        testResultsFiles: "**/surefire-reports/TEST-*.xml"
        checkStyleRunAnalysis: true
        pmdRunAnalysis: true
        findBugsRunAnalysis: true
        goals: "package"

  - job: Saludo
    steps:
      - script: echo Hola amigos!
        displayName: Hola amigos

  - job: Build
    steps:
      - script: ls
      - script: pwd
      - script: mvn clean install
