trigger: RobertoRamirez
pool: vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: A
    steps:
    - script: 
      echo "Building"
      echo "Building finished"

 - stage: Install maven
   jobs:
   - job: test
     steps:
     - task: Maven@3
       inputs:
       mavenPOMFile: 'pom.xml'
       mavenOptions:'-Xmx3072m' 
       testResultsFiles: '**/surefire-reports/TEST-*.xml' 
       javaHomeOption: 'JDKVersion'
       jdkVersionOption: '1.11'
       jdkArchitectureOption: 'x64'
       mavenVersionOption: 'Default'
       publishResultFiles: true
       testResultsFiles: '**/surefire-reports/TEST-*.xml'
       goals: 'package' 

- stage: Deployment
  jobs:
  - job: Deploying
    steps:
    - script: mvn clean install

- stage: Test
  jobs:
  - job: Deploying
    steps:
    - script: mvn test

- stage: Static Code Analysis
  Jobs:
  - Job: Analysis
    steps:
    - script: mvn pmd:pmd findbugs:findbugs checkstyle:checkstyle
