resources:
    repositories:
    - repository: simple-java-maven-app
      type: github
      endpoint: github-service-connection
      name: simple-java-maven-app
      ref: refs/heads/main

trigger: 
- AndresRamirez

pool:
    vmImage: 'ubuntu-latest'
    
stages:
- stage:
  displayName: 'Build, Test, and Package Stage'

  jobs:
  - job: 'Build_Maven'
    displayName: 'Build, Test, and Package Maven'
    
    steps: 
        - checkout: simple-java-maven-app
        
        -   task maven@3
            inputs:
              goals: 'clean install'
              checkStyleRunAnalysis: true
              pmdRunAnalysis: true
              findBugsAnalysis: true
        
        - script: |
	      mv tagert/*.jar  target/myapp/

	    - publish: $(System.DefaultWorkingDirectory)/target/*.jar
	      artifact: my-app.jar
      
- stage: Hello
  jobs:
  - steps: 
    - script: echo Hi all
      displayName: 'Run a one-line-script'
  
- stage: Good morning
  - job: 
    steps:
    - script: echo so good, so good, so good
      displayName: 'Run a one-line-script'
     
- stage: Bye
  - job: 
    steps:
    - script: echo Good night
      displayName: 'Run a one-line-script'
